spring:
  application:
    name: 'learn-spring'
  thymeleaf:
    cache: false
    enabled: true
    prefix: 'classpath:/templates/'
    suffix: .html
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1'
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
  file:
    name: 'logs/app.log'

server:
  port: 8081
